

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simple-bank-api
    ports:
      - "8080:8080"
    env_file:
      - app.env
    command: ["/app/main"]
    restart: always


