@baseUrl = http://localhost:8080
@access_token = v2.local.KiMpFl_PBzjjylaqzpbsMf1HKZuCggcdBjI355GD6xuaC2x_WTiSoW_D5wSqu6h74IvepUDAcjrWc1pyC6ftKEiXZ2MLJ2XPOn_MH0GHt8pcOudxWvV11OYjyuj101vX72_Hbk7zCDD-oXiBMoKdWVCldEyQ6-EWHwzzU04CkamA41vy_qerUtycnSJ6US_17Ozo0fmxlzbweWHk3QoA-ewSNQjXwv2v51ZJHSNOqFSLZBPhtpNeqSTrf8PUGlUCVdjd9ZVIiw.bnVsbA
@refresh_token = v2.local.xn4MA8PMPTAf0g1pchRf_3pA-6IYfac1dD2QhGluYzNfJMkT-EPDuzjD273Mlnzzn_wIe5y4k7k5goYZQVLfNWj_EgYvSgxYvGdrvM13YwOWdF9E46gpGoFawf4EWqNYWruHqbSH3tXjQoeVkLe3jyiiLpxUEkaUEyYxYdfUAxLpAtkG1TpomI5JtbmYGaITbMvTjykRM1Mshec8S3Vr3uOmu0cUXEHGJr9kXIBWc5wnm987YErbPSXxUNyFv_Dp9cvQfhVOkw.bnVsbA


### Renew access token
POST {{baseUrl}}/tokens/renew_access
Content-Type: application/json

{
  "refresh_token": "{{refresh_token}}"
}


### Login user
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "username": "bob",
  "password": "secret123"
}



### Create user
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "bob",
  "password": "secret123",
  "full_name": "Bob Drake",
  "email": "bob@example.com"
}


###
POST http://localhost:8080/transfers
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "from_account_id": 155,
  "to_account_id": 150,
  "amount": 100,
  "currency": "EUR"
}


### List accounts – page 1
GET http://localhost:8080/accounts?page_id=1&page_size=9
Authorization: Bearer {{access_token}}


### ❌ Invalid page_id
GET http://localhost:8080/accounts?page_id=0&page_size=5


### ❌ Invalid page_size
GET http://localhost:8080/accounts?page_id=1&page_size=100

###
GET http://localhost:8080/accounts?page_id=10000&page_size=5


### Get account by ID
GET http://localhost:8080/accounts/14


### ❌ Invalid ID
GET http://localhost:8080/accounts/abc


### ❌ Not found
GET http://localhost:8080/accounts/999999

###
GET http://localhost:8080/accounts/-1




### Health check (optional)
GET http://localhost:8080/ping


### Create account – USD
POST http://localhost:8080/accounts
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "currency": "EUR"
}


### Create account – EUR
POST http://localhost:8080/accounts
Content-Type: application/json

{
  "owner": "bob",
  "currency": "EUR"
}


### ❌ Invalid currency (should return 400)
POST http://localhost:8080/accounts
Content-Type: application/json

{
  "owner": "charlie",
  "currency": "VND"
}


### ❌ Missing owner (should return 400)
POST http://localhost:8080/accounts
Content-Type: application/json

{
  "currency": "USD"
}
