// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pb/v1/filter_message.proto

package pbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxPriceUsd   float64                `protobuf:"fixed64,1,opt,name=max_price_usd,json=maxPriceUsd,proto3" json:"max_price_usd,omitempty"`
	MinCpuCores   uint32                 `protobuf:"varint,2,opt,name=min_cpu_cores,json=minCpuCores,proto3" json:"min_cpu_cores,omitempty"`
	MinCpuGhz     float64                `protobuf:"fixed64,3,opt,name=min_cpu_ghz,json=minCpuGhz,proto3" json:"min_cpu_ghz,omitempty"`
	MinRam        *Memory                `protobuf:"bytes,4,opt,name=min_ram,json=minRam,proto3" json:"min_ram,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_pb_v1_filter_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_filter_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_pb_v1_filter_message_proto_rawDescGZIP(), []int{0}
}

func (x *Filter) GetMaxPriceUsd() float64 {
	if x != nil {
		return x.MaxPriceUsd
	}
	return 0
}

func (x *Filter) GetMinCpuCores() uint32 {
	if x != nil {
		return x.MinCpuCores
	}
	return 0
}

func (x *Filter) GetMinCpuGhz() float64 {
	if x != nil {
		return x.MinCpuGhz
	}
	return 0
}

func (x *Filter) GetMinRam() *Memory {
	if x != nil {
		return x.MinRam
	}
	return nil
}

var File_pb_v1_filter_message_proto protoreflect.FileDescriptor

const file_pb_v1_filter_message_proto_rawDesc = "" +
	"\n" +
	"\x1apb/v1/filter_message.proto\x12\x05pb.v1\x1a\x1apb/v1/memory_message.proto\"\x98\x01\n" +
	"\x06Filter\x12\"\n" +
	"\rmax_price_usd\x18\x01 \x01(\x01R\vmaxPriceUsd\x12\"\n" +
	"\rmin_cpu_cores\x18\x02 \x01(\rR\vminCpuCores\x12\x1e\n" +
	"\vmin_cpu_ghz\x18\x03 \x01(\x01R\tminCpuGhz\x12&\n" +
	"\amin_ram\x18\x04 \x01(\v2\r.pb.v1.MemoryR\x06minRamB0Z.github.com/thinhcompany/simple-bank/pb/v1;pbv1b\x06proto3"

var (
	file_pb_v1_filter_message_proto_rawDescOnce sync.Once
	file_pb_v1_filter_message_proto_rawDescData []byte
)

func file_pb_v1_filter_message_proto_rawDescGZIP() []byte {
	file_pb_v1_filter_message_proto_rawDescOnce.Do(func() {
		file_pb_v1_filter_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_v1_filter_message_proto_rawDesc), len(file_pb_v1_filter_message_proto_rawDesc)))
	})
	return file_pb_v1_filter_message_proto_rawDescData
}

var file_pb_v1_filter_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_v1_filter_message_proto_goTypes = []any{
	(*Filter)(nil), // 0: pb.v1.Filter
	(*Memory)(nil), // 1: pb.v1.Memory
}
var file_pb_v1_filter_message_proto_depIdxs = []int32{
	1, // 0: pb.v1.Filter.min_ram:type_name -> pb.v1.Memory
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_v1_filter_message_proto_init() }
func file_pb_v1_filter_message_proto_init() {
	if File_pb_v1_filter_message_proto != nil {
		return
	}
	file_pb_v1_memory_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_v1_filter_message_proto_rawDesc), len(file_pb_v1_filter_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_v1_filter_message_proto_goTypes,
		DependencyIndexes: file_pb_v1_filter_message_proto_depIdxs,
		MessageInfos:      file_pb_v1_filter_message_proto_msgTypes,
	}.Build()
	File_pb_v1_filter_message_proto = out.File
	file_pb_v1_filter_message_proto_goTypes = nil
	file_pb_v1_filter_message_proto_depIdxs = nil
}
