// simple-bank/proto/pb/v1/keyboard_message.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pb/v1/keyboard_message.proto

package pbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Keyboard_Layout int32

const (
	Keyboard_LAYOUT_UNSPECIFIED Keyboard_Layout = 0
	Keyboard_LAYOUT_QWERTY      Keyboard_Layout = 1
	Keyboard_LAYOUT_QWERTZ      Keyboard_Layout = 2
	Keyboard_LAYOUT_AZERTY      Keyboard_Layout = 3
)

// Enum value maps for Keyboard_Layout.
var (
	Keyboard_Layout_name = map[int32]string{
		0: "LAYOUT_UNSPECIFIED",
		1: "LAYOUT_QWERTY",
		2: "LAYOUT_QWERTZ",
		3: "LAYOUT_AZERTY",
	}
	Keyboard_Layout_value = map[string]int32{
		"LAYOUT_UNSPECIFIED": 0,
		"LAYOUT_QWERTY":      1,
		"LAYOUT_QWERTZ":      2,
		"LAYOUT_AZERTY":      3,
	}
)

func (x Keyboard_Layout) Enum() *Keyboard_Layout {
	p := new(Keyboard_Layout)
	*p = x
	return p
}

func (x Keyboard_Layout) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Keyboard_Layout) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_v1_keyboard_message_proto_enumTypes[0].Descriptor()
}

func (Keyboard_Layout) Type() protoreflect.EnumType {
	return &file_pb_v1_keyboard_message_proto_enumTypes[0]
}

func (x Keyboard_Layout) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Keyboard_Layout.Descriptor instead.
func (Keyboard_Layout) EnumDescriptor() ([]byte, []int) {
	return file_pb_v1_keyboard_message_proto_rawDescGZIP(), []int{0, 0}
}

type Keyboard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Layout        Keyboard_Layout        `protobuf:"varint,1,opt,name=layout,proto3,enum=pb.v1.Keyboard_Layout" json:"layout,omitempty"`
	Backlit       bool                   `protobuf:"varint,2,opt,name=backlit,proto3" json:"backlit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Keyboard) Reset() {
	*x = Keyboard{}
	mi := &file_pb_v1_keyboard_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Keyboard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Keyboard) ProtoMessage() {}

func (x *Keyboard) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_keyboard_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Keyboard.ProtoReflect.Descriptor instead.
func (*Keyboard) Descriptor() ([]byte, []int) {
	return file_pb_v1_keyboard_message_proto_rawDescGZIP(), []int{0}
}

func (x *Keyboard) GetLayout() Keyboard_Layout {
	if x != nil {
		return x.Layout
	}
	return Keyboard_LAYOUT_UNSPECIFIED
}

func (x *Keyboard) GetBacklit() bool {
	if x != nil {
		return x.Backlit
	}
	return false
}

var File_pb_v1_keyboard_message_proto protoreflect.FileDescriptor

const file_pb_v1_keyboard_message_proto_rawDesc = "" +
	"\n" +
	"\x1cpb/v1/keyboard_message.proto\x12\x05pb.v1\"\xaf\x01\n" +
	"\bKeyboard\x12.\n" +
	"\x06layout\x18\x01 \x01(\x0e2\x16.pb.v1.Keyboard.LayoutR\x06layout\x12\x18\n" +
	"\abacklit\x18\x02 \x01(\bR\abacklit\"Y\n" +
	"\x06Layout\x12\x16\n" +
	"\x12LAYOUT_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rLAYOUT_QWERTY\x10\x01\x12\x11\n" +
	"\rLAYOUT_QWERTZ\x10\x02\x12\x11\n" +
	"\rLAYOUT_AZERTY\x10\x03B0Z.github.com/thinhcompany/simple-bank/pb/v1;pbv1b\x06proto3"

var (
	file_pb_v1_keyboard_message_proto_rawDescOnce sync.Once
	file_pb_v1_keyboard_message_proto_rawDescData []byte
)

func file_pb_v1_keyboard_message_proto_rawDescGZIP() []byte {
	file_pb_v1_keyboard_message_proto_rawDescOnce.Do(func() {
		file_pb_v1_keyboard_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_v1_keyboard_message_proto_rawDesc), len(file_pb_v1_keyboard_message_proto_rawDesc)))
	})
	return file_pb_v1_keyboard_message_proto_rawDescData
}

var file_pb_v1_keyboard_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_v1_keyboard_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_v1_keyboard_message_proto_goTypes = []any{
	(Keyboard_Layout)(0), // 0: pb.v1.Keyboard.Layout
	(*Keyboard)(nil),     // 1: pb.v1.Keyboard
}
var file_pb_v1_keyboard_message_proto_depIdxs = []int32{
	0, // 0: pb.v1.Keyboard.layout:type_name -> pb.v1.Keyboard.Layout
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_v1_keyboard_message_proto_init() }
func file_pb_v1_keyboard_message_proto_init() {
	if File_pb_v1_keyboard_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_v1_keyboard_message_proto_rawDesc), len(file_pb_v1_keyboard_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_v1_keyboard_message_proto_goTypes,
		DependencyIndexes: file_pb_v1_keyboard_message_proto_depIdxs,
		EnumInfos:         file_pb_v1_keyboard_message_proto_enumTypes,
		MessageInfos:      file_pb_v1_keyboard_message_proto_msgTypes,
	}.Build()
	File_pb_v1_keyboard_message_proto = out.File
	file_pb_v1_keyboard_message_proto_goTypes = nil
	file_pb_v1_keyboard_message_proto_depIdxs = nil
}
