// simple-bank/proto/pb/v1/memory_message.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pb/v1/memory_message.proto

package pbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Memory_Unit int32

const (
	Memory_UNIT_UNSPECIFIED Memory_Unit = 0
	Memory_UNIT_BIT         Memory_Unit = 1
	Memory_UNIT_BYTE        Memory_Unit = 2
	Memory_UNIT_KILOBYTE    Memory_Unit = 3
	Memory_UNIT_MEGABYTE    Memory_Unit = 4
	Memory_UNIT_GIGABYTE    Memory_Unit = 5
	Memory_UNIT_TERABYTE    Memory_Unit = 6
)

// Enum value maps for Memory_Unit.
var (
	Memory_Unit_name = map[int32]string{
		0: "UNIT_UNSPECIFIED",
		1: "UNIT_BIT",
		2: "UNIT_BYTE",
		3: "UNIT_KILOBYTE",
		4: "UNIT_MEGABYTE",
		5: "UNIT_GIGABYTE",
		6: "UNIT_TERABYTE",
	}
	Memory_Unit_value = map[string]int32{
		"UNIT_UNSPECIFIED": 0,
		"UNIT_BIT":         1,
		"UNIT_BYTE":        2,
		"UNIT_KILOBYTE":    3,
		"UNIT_MEGABYTE":    4,
		"UNIT_GIGABYTE":    5,
		"UNIT_TERABYTE":    6,
	}
)

func (x Memory_Unit) Enum() *Memory_Unit {
	p := new(Memory_Unit)
	*p = x
	return p
}

func (x Memory_Unit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Memory_Unit) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_v1_memory_message_proto_enumTypes[0].Descriptor()
}

func (Memory_Unit) Type() protoreflect.EnumType {
	return &file_pb_v1_memory_message_proto_enumTypes[0]
}

func (x Memory_Unit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Memory_Unit.Descriptor instead.
func (Memory_Unit) EnumDescriptor() ([]byte, []int) {
	return file_pb_v1_memory_message_proto_rawDescGZIP(), []int{0, 0}
}

type Memory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         uint64                 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Unit          Memory_Unit            `protobuf:"varint,2,opt,name=unit,proto3,enum=pb.v1.Memory_Unit" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Memory) Reset() {
	*x = Memory{}
	mi := &file_pb_v1_memory_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Memory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Memory) ProtoMessage() {}

func (x *Memory) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_memory_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Memory.ProtoReflect.Descriptor instead.
func (*Memory) Descriptor() ([]byte, []int) {
	return file_pb_v1_memory_message_proto_rawDescGZIP(), []int{0}
}

func (x *Memory) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Memory) GetUnit() Memory_Unit {
	if x != nil {
		return x.Unit
	}
	return Memory_UNIT_UNSPECIFIED
}

var File_pb_v1_memory_message_proto protoreflect.FileDescriptor

const file_pb_v1_memory_message_proto_rawDesc = "" +
	"\n" +
	"\x1apb/v1/memory_message.proto\x12\x05pb.v1\"\xce\x01\n" +
	"\x06Memory\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x04R\x05value\x12&\n" +
	"\x04unit\x18\x02 \x01(\x0e2\x12.pb.v1.Memory.UnitR\x04unit\"\x85\x01\n" +
	"\x04Unit\x12\x14\n" +
	"\x10UNIT_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bUNIT_BIT\x10\x01\x12\r\n" +
	"\tUNIT_BYTE\x10\x02\x12\x11\n" +
	"\rUNIT_KILOBYTE\x10\x03\x12\x11\n" +
	"\rUNIT_MEGABYTE\x10\x04\x12\x11\n" +
	"\rUNIT_GIGABYTE\x10\x05\x12\x11\n" +
	"\rUNIT_TERABYTE\x10\x06B0Z.github.com/thinhcompany/simple-bank/pb/v1;pbv1b\x06proto3"

var (
	file_pb_v1_memory_message_proto_rawDescOnce sync.Once
	file_pb_v1_memory_message_proto_rawDescData []byte
)

func file_pb_v1_memory_message_proto_rawDescGZIP() []byte {
	file_pb_v1_memory_message_proto_rawDescOnce.Do(func() {
		file_pb_v1_memory_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_v1_memory_message_proto_rawDesc), len(file_pb_v1_memory_message_proto_rawDesc)))
	})
	return file_pb_v1_memory_message_proto_rawDescData
}

var file_pb_v1_memory_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_v1_memory_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_v1_memory_message_proto_goTypes = []any{
	(Memory_Unit)(0), // 0: pb.v1.Memory.Unit
	(*Memory)(nil),   // 1: pb.v1.Memory
}
var file_pb_v1_memory_message_proto_depIdxs = []int32{
	0, // 0: pb.v1.Memory.unit:type_name -> pb.v1.Memory.Unit
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_v1_memory_message_proto_init() }
func file_pb_v1_memory_message_proto_init() {
	if File_pb_v1_memory_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_v1_memory_message_proto_rawDesc), len(file_pb_v1_memory_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_v1_memory_message_proto_goTypes,
		DependencyIndexes: file_pb_v1_memory_message_proto_depIdxs,
		EnumInfos:         file_pb_v1_memory_message_proto_enumTypes,
		MessageInfos:      file_pb_v1_memory_message_proto_msgTypes,
	}.Build()
	File_pb_v1_memory_message_proto = out.File
	file_pb_v1_memory_message_proto_goTypes = nil
	file_pb_v1_memory_message_proto_depIdxs = nil
}
