// simple-bank/proto/pb/v1/service_simple_bank.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pb/v1/service_simple_bank.proto

package pbv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_pb_v1_service_simple_bank_proto protoreflect.FileDescriptor

const file_pb_v1_service_simple_bank_proto_rawDesc = "" +
	"\n" +
	"\x1fpb/v1/service_simple_bank.proto\x12\x05pb.v1\x1a\x1bpb/v1/rpc_create_user.proto\x1a\x1apb/v1/rpc_login_user.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xef\x02\n" +
	"\x11SimpleBankService\x12\xa0\x01\n" +
	"\n" +
	"CreateUser\x12\x18.pb.v1.CreateUserRequest\x1a\x19.pb.v1.CreateUserResponse\"]\x92AF\x12\x0fCreate new user\x1a3Create a new user with username, email and password\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/users\x12\x94\x01\n" +
	"\tLoginUser\x12\x17.pb.v1.LoginUserRequest\x1a\x18.pb.v1.LoginUserResponse\"T\x92A7\x12\n" +
	"Login user\x1a)Authenticate user and return access token\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/users/login\x1a \x92A\x1d\n" +
	"\x05Users\x12\x14User management APIsB0Z.github.com/thinhcompany/simple-bank/pb/v1;pbv1b\x06proto3"

var file_pb_v1_service_simple_bank_proto_goTypes = []any{
	(*CreateUserRequest)(nil),  // 0: pb.v1.CreateUserRequest
	(*LoginUserRequest)(nil),   // 1: pb.v1.LoginUserRequest
	(*CreateUserResponse)(nil), // 2: pb.v1.CreateUserResponse
	(*LoginUserResponse)(nil),  // 3: pb.v1.LoginUserResponse
}
var file_pb_v1_service_simple_bank_proto_depIdxs = []int32{
	0, // 0: pb.v1.SimpleBankService.CreateUser:input_type -> pb.v1.CreateUserRequest
	1, // 1: pb.v1.SimpleBankService.LoginUser:input_type -> pb.v1.LoginUserRequest
	2, // 2: pb.v1.SimpleBankService.CreateUser:output_type -> pb.v1.CreateUserResponse
	3, // 3: pb.v1.SimpleBankService.LoginUser:output_type -> pb.v1.LoginUserResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_v1_service_simple_bank_proto_init() }
func file_pb_v1_service_simple_bank_proto_init() {
	if File_pb_v1_service_simple_bank_proto != nil {
		return
	}
	file_pb_v1_rpc_create_user_proto_init()
	file_pb_v1_rpc_login_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_v1_service_simple_bank_proto_rawDesc), len(file_pb_v1_service_simple_bank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_v1_service_simple_bank_proto_goTypes,
		DependencyIndexes: file_pb_v1_service_simple_bank_proto_depIdxs,
	}.Build()
	File_pb_v1_service_simple_bank_proto = out.File
	file_pb_v1_service_simple_bank_proto_goTypes = nil
	file_pb_v1_service_simple_bank_proto_depIdxs = nil
}
