// simple-bank/proto/pb/v1/storage_message.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pb/v1/storage_message.proto

package pbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Storage_Driver int32

const (
	Storage_DRIVER_UNSPECIFIED Storage_Driver = 0
	Storage_DRIVER_HDD         Storage_Driver = 1
	Storage_DRIVER_SSD         Storage_Driver = 2
)

// Enum value maps for Storage_Driver.
var (
	Storage_Driver_name = map[int32]string{
		0: "DRIVER_UNSPECIFIED",
		1: "DRIVER_HDD",
		2: "DRIVER_SSD",
	}
	Storage_Driver_value = map[string]int32{
		"DRIVER_UNSPECIFIED": 0,
		"DRIVER_HDD":         1,
		"DRIVER_SSD":         2,
	}
)

func (x Storage_Driver) Enum() *Storage_Driver {
	p := new(Storage_Driver)
	*p = x
	return p
}

func (x Storage_Driver) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Storage_Driver) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_v1_storage_message_proto_enumTypes[0].Descriptor()
}

func (Storage_Driver) Type() protoreflect.EnumType {
	return &file_pb_v1_storage_message_proto_enumTypes[0]
}

func (x Storage_Driver) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Storage_Driver.Descriptor instead.
func (Storage_Driver) EnumDescriptor() ([]byte, []int) {
	return file_pb_v1_storage_message_proto_rawDescGZIP(), []int{0, 0}
}

type Storage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Driver        Storage_Driver         `protobuf:"varint,1,opt,name=driver,proto3,enum=pb.v1.Storage_Driver" json:"driver,omitempty"`
	Memory        *Memory                `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Storage) Reset() {
	*x = Storage{}
	mi := &file_pb_v1_storage_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Storage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Storage) ProtoMessage() {}

func (x *Storage) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_storage_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Storage.ProtoReflect.Descriptor instead.
func (*Storage) Descriptor() ([]byte, []int) {
	return file_pb_v1_storage_message_proto_rawDescGZIP(), []int{0}
}

func (x *Storage) GetDriver() Storage_Driver {
	if x != nil {
		return x.Driver
	}
	return Storage_DRIVER_UNSPECIFIED
}

func (x *Storage) GetMemory() *Memory {
	if x != nil {
		return x.Memory
	}
	return nil
}

var File_pb_v1_storage_message_proto protoreflect.FileDescriptor

const file_pb_v1_storage_message_proto_rawDesc = "" +
	"\n" +
	"\x1bpb/v1/storage_message.proto\x12\x05pb.v1\x1a\x1apb/v1/memory_message.proto\"\xa1\x01\n" +
	"\aStorage\x12-\n" +
	"\x06driver\x18\x01 \x01(\x0e2\x15.pb.v1.Storage.DriverR\x06driver\x12%\n" +
	"\x06memory\x18\x02 \x01(\v2\r.pb.v1.MemoryR\x06memory\"@\n" +
	"\x06Driver\x12\x16\n" +
	"\x12DRIVER_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"DRIVER_HDD\x10\x01\x12\x0e\n" +
	"\n" +
	"DRIVER_SSD\x10\x02B0Z.github.com/thinhcompany/simple-bank/pb/v1;pbv1b\x06proto3"

var (
	file_pb_v1_storage_message_proto_rawDescOnce sync.Once
	file_pb_v1_storage_message_proto_rawDescData []byte
)

func file_pb_v1_storage_message_proto_rawDescGZIP() []byte {
	file_pb_v1_storage_message_proto_rawDescOnce.Do(func() {
		file_pb_v1_storage_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_v1_storage_message_proto_rawDesc), len(file_pb_v1_storage_message_proto_rawDesc)))
	})
	return file_pb_v1_storage_message_proto_rawDescData
}

var file_pb_v1_storage_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_v1_storage_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_v1_storage_message_proto_goTypes = []any{
	(Storage_Driver)(0), // 0: pb.v1.Storage.Driver
	(*Storage)(nil),     // 1: pb.v1.Storage
	(*Memory)(nil),      // 2: pb.v1.Memory
}
var file_pb_v1_storage_message_proto_depIdxs = []int32{
	0, // 0: pb.v1.Storage.driver:type_name -> pb.v1.Storage.Driver
	2, // 1: pb.v1.Storage.memory:type_name -> pb.v1.Memory
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_v1_storage_message_proto_init() }
func file_pb_v1_storage_message_proto_init() {
	if File_pb_v1_storage_message_proto != nil {
		return
	}
	file_pb_v1_memory_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_v1_storage_message_proto_rawDesc), len(file_pb_v1_storage_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_v1_storage_message_proto_goTypes,
		DependencyIndexes: file_pb_v1_storage_message_proto_depIdxs,
		EnumInfos:         file_pb_v1_storage_message_proto_enumTypes,
		MessageInfos:      file_pb_v1_storage_message_proto_msgTypes,
	}.Build()
	File_pb_v1_storage_message_proto = out.File
	file_pb_v1_storage_message_proto_goTypes = nil
	file_pb_v1_storage_message_proto_depIdxs = nil
}
