// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: verify_email.sql

package db

import (
	"context"
	"time"
)

const createVerifyEmail = `-- name: CreateVerifyEmail :one
INSERT INTO verify_emails (
  username,
  email,
  secret_code,
  expired_at
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, username, email, secret_code, is_used, created_at, expired_at
`

type CreateVerifyEmailParams struct {
	Username   string    `json:"username"`
	Email      string    `json:"email"`
	SecretCode string    `json:"secret_code"`
	ExpiredAt  time.Time `json:"expired_at"`
}

func (q *Queries) CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (VerifyEmails, error) {
	row := q.db.QueryRowContext(ctx, createVerifyEmail,
		arg.Username,
		arg.Email,
		arg.SecretCode,
		arg.ExpiredAt,
	)
	var i VerifyEmails
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.SecretCode,
		&i.IsUsed,
		&i.CreatedAt,
		&i.ExpiredAt,
	)
	return i, err
}

const getVerifyEmailByID = `-- name: GetVerifyEmailByID :one
SELECT id, username, email, secret_code, is_used, created_at, expired_at
FROM verify_emails
WHERE id = $1
`

func (q *Queries) GetVerifyEmailByID(ctx context.Context, id int64) (VerifyEmails, error) {
	row := q.db.QueryRowContext(ctx, getVerifyEmailByID, id)
	var i VerifyEmails
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.SecretCode,
		&i.IsUsed,
		&i.CreatedAt,
		&i.ExpiredAt,
	)
	return i, err
}

const getVerifyEmailBySecretCode = `-- name: GetVerifyEmailBySecretCode :one
SELECT id, username, email, secret_code, is_used, created_at, expired_at
FROM verify_emails
WHERE secret_code = $1
  AND is_used = false
  AND expired_at > now()
`

func (q *Queries) GetVerifyEmailBySecretCode(ctx context.Context, secretCode string) (VerifyEmails, error) {
	row := q.db.QueryRowContext(ctx, getVerifyEmailBySecretCode, secretCode)
	var i VerifyEmails
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.SecretCode,
		&i.IsUsed,
		&i.CreatedAt,
		&i.ExpiredAt,
	)
	return i, err
}

const markVerifyEmailUsed = `-- name: MarkVerifyEmailUsed :exec
UPDATE verify_emails
SET is_used = true
WHERE id = $1
`

func (q *Queries) MarkVerifyEmailUsed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markVerifyEmailUsed, id)
	return err
}

const verifyUserEmailTx = `-- name: VerifyUserEmailTx :exec
UPDATE users
SET is_email_verified = true
WHERE username = $1
`

func (q *Queries) VerifyUserEmailTx(ctx context.Context, username string) error {
	_, err := q.db.ExecContext(ctx, verifyUserEmailTx, username)
	return err
}
