[ req ]
default_bits       = 4096
prompt             = no
default_md         = sha256
distinguished_name = dn
x509_extensions    = v3_ca

[ dn ]
C  = VN
ST = LongAn
L  = HoChiMinh
O  = thinhcompany
OU = education
CN = thinhcompany Root CA
emailAddress = thinhpro@gmail.com

[ v3_ca ]
basicConstraints = critical, CA:TRUE
keyUsage = critical, digitalSignature, cRLSign, keyCertSign
subjectKeyIdentifier = hash