[ req ]
default_bits       = 4096
prompt             = no
default_md         = sha256
distinguished_name = dn
req_extensions     = req_ext

[ dn ]
C  = VN
ST = LongAn
L  = HoChiMinh
O  = thinhcompany
OU = client
CN = simple-bank-client

[ req_ext ]
keyUsage = digitalSignature
extendedKeyUsage = clientAuth