upstream simple_bank_service {
    least_conn;
    server 127.0.0.1:50051;
    server 127.0.0.1:50052;
}

server {
    listen 8080 ssl http2;

    ssl_certificate         /etc/nginx/cert/server-cert.pem;
    ssl_certificate_key     /etc/nginx/cert/server-key.pem;
    ssl_client_certificate  /etc/nginx/cert/ca-cert.pem;
    ssl_verify_client       on;

    location / {
        grpc_pass grpc://simple_bank_service;

        grpc_set_header Host $host;
        grpc_set_header X-Real-IP $remote_addr;
    }
}
